name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint_markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1.4.0
        with:
          config: '.markdownlint.json'
          args: '**/*.md'

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: straw-hat-team/github-actions-workflows/nodejs/setup@v1.6.4
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - uses: straw-hat-team/github-actions-workflows/nodejs/prettier@v1.6.4
        with:
          sht-npm-token: ${{ secrets.SHT_NPM_TOKEN }}
