name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint_markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avto-dev/markdown-lint@v1.4.0
        with:
          config: '.markdownlint.json'
          args: '**/*.md'

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions
      - shell: sh
        run: yarn install --immutable
        env:
          SHT_NPM_TOKEN: ${{ secrets.SHT_NPM_TOKEN }}
      - shell: sh
        run: yarn lint:format:prettier
      - shell: sh
        run: yarn lint:spectral:openapi:petstore
